/*
 * The MIT License
 *
 * Copyright 2021 shoaib.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.shoaibkhan.modmanager.gui.dialog;

/**
 *
 * @author shoaib
 */
public class ChooseVersionDialog extends javax.swing.JDialog {

    private boolean hasChoosen = false;

    /**
     * Creates new form ChooseVersionDialog
     *
     * @param parent
     * @param modal
     */
    public ChooseVersionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public int choose(Object[] versions) {

        // Remove all items in the combo box
        versionComboBox.removeAllItems();

        // Add items from versions array to the combo box
        for (int i = 0; i < versions.length; i++) {
            Object version = versions[i];
            if (i == 0) {
                versionComboBox.addItem((String) version + " (latest)");
            } else {
                versionComboBox.addItem((String) version);
            }
        }
        
        // Resize after adding
        pack();
        revalidate();

        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL); // This stops the thread when setVisible(true) is called
        setVisible(true);

        if (hasChoosen) {
            // Get and return the choice
            int choice = versionComboBox.getSelectedIndex();
            return choice;
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        row1 = new javax.swing.JPanel();
        headingLabel = new com.shoaibkhan.modmanager.gui.widgets.base.BaseLabel();
        versionComboBox = new javax.swing.JComboBox<>();
        row2 = new javax.swing.JPanel();
        confirmButton = new com.shoaibkhan.modmanager.gui.widgets.base.BaseButton();
        cancelButton = new com.shoaibkhan.modmanager.gui.widgets.base.BaseButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Version");
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.Y_AXIS));

        headingLabel.setText("Select Mod Version:-  ");
        headingLabel.setName(""); // NOI18N
        row1.add(headingLabel);

        versionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Default" }));
        row1.add(versionComboBox);

        container.add(row1);

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        row2.add(confirmButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        row2.add(cancelButton);

        container.add(row2);

        getContentPane().add(container);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // Close dialog and set has chosen to true
        hasChoosen = true;
        dispose();
        setVisible(false);
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Close dialog but don't set has chosen to true to set the response/return to -1
        dispose();
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shoaibkhan.modmanager.gui.widgets.base.BaseButton cancelButton;
    private com.shoaibkhan.modmanager.gui.widgets.base.BaseButton confirmButton;
    private javax.swing.JPanel container;
    private com.shoaibkhan.modmanager.gui.widgets.base.BaseLabel headingLabel;
    private javax.swing.JPanel row1;
    private javax.swing.JPanel row2;
    private javax.swing.JComboBox<String> versionComboBox;
    // End of variables declaration//GEN-END:variables

}
