/*
 * The MIT License
 *
 * Copyright 2021 shoaib.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.shoaibkhan.modmanager.gui.panels;

/**
 *
 * @author shoaib
 */
public class ModsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ModsPanel
     */
    public ModsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new com.shoaibkhan.modmanager.gui.widgets.base.BaseLabel();
        modsComboBox = new com.shoaibkhan.modmanager.gui.widgets.mods.ModsComboBox();
        installUnistallButton = new com.shoaibkhan.modmanager.gui.widgets.mods.InstallOrUninstallButton();
        changeVersionButton = new com.shoaibkhan.modmanager.gui.widgets.mods.ChangeVersionButton();

        setNextFocusableComponent(headingLabel);

        headingLabel.setLabelFor(modsComboBox);
        headingLabel.setText("Select Mod:-  ");
        headingLabel.setNextFocusableComponent(modsComboBox);
        add(headingLabel);

        modsComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        modsComboBox.setNextFocusableComponent(installUnistallButton);
        modsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modsComboBoxActionPerformed(evt);
            }
        });
        add(modsComboBox);

        installUnistallButton.setNextFocusableComponent(changeVersionButton);
        add(installUnistallButton);

        changeVersionButton.setText("Change Version");
        add(changeVersionButton);
    }// </editor-fold>//GEN-END:initComponents

    private void iouButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iouButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iouButton1ActionPerformed

    private void modsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modsComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shoaibkhan.modmanager.gui.widgets.mods.ChangeVersionButton changeVersionButton;
    private com.shoaibkhan.modmanager.gui.widgets.base.BaseLabel headingLabel;
    public static com.shoaibkhan.modmanager.gui.widgets.mods.InstallOrUninstallButton installUnistallButton;
    public static com.shoaibkhan.modmanager.gui.widgets.mods.ModsComboBox modsComboBox;
    // End of variables declaration//GEN-END:variables
}
