/*
 * The MIT License
 *
 * Copyright 2021 shoaib.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.shoaibkhan.modmanager.gui.panels;

/**
 * @author shoaib
 */
public class ProfilesPanel extends javax.swing.JPanel {

//    public static ProfilesComboBox profilesComboBox;

    /**
     * Creates new form NewPanel
     */
    public ProfilesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hLabel = new com.shoaibkhan.modmanager.gui.widgets.base.BaseLabel();
        profilesComboBox = new com.shoaibkhan.modmanager.gui.widgets.profile.ProfilesComboBox();
        addProfileButton = new com.shoaibkhan.modmanager.gui.widgets.profile.AddProfileButton();
        removeProfileButton = new com.shoaibkhan.modmanager.gui.widgets.profile.RemoveProfileButton();

        setNextFocusableComponent(hLabel);

        hLabel.setLabelFor(profilesComboBox);
        hLabel.setText("Select Profile:-   ");
        hLabel.setNextFocusableComponent(profilesComboBox);
        add(hLabel);

        profilesComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        profilesComboBox.setNextFocusableComponent(addProfileButton);
        add(profilesComboBox);

        addProfileButton.setText("Add Profile");
        addProfileButton.setToolTipText("");
        addProfileButton.setNextFocusableComponent(removeProfileButton);
        addProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfileButtonActionPerformed(evt);
            }
        });
        add(addProfileButton);

        removeProfileButton.setText("Remove Profile");
        add(removeProfileButton);
    }// </editor-fold>//GEN-END:initComponents

    private void addProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProfileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shoaibkhan.modmanager.gui.widgets.profile.AddProfileButton addProfileButton;
    public static com.shoaibkhan.modmanager.gui.widgets.base.BaseLabel hLabel;
    public static com.shoaibkhan.modmanager.gui.widgets.profile.ProfilesComboBox profilesComboBox;
    private com.shoaibkhan.modmanager.gui.widgets.profile.RemoveProfileButton removeProfileButton;
    // End of variables declaration//GEN-END:variables
}
