/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shoaibkhan.modmanager.gui.panels;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author shoaib
 */
public class ProfilesPanel extends javax.swing.JPanel {

//    public static ProfilesComboBox profilesComboBox;

    /**
     * Creates new form NewPanel
     */
    public ProfilesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hLabel = new com.shoaibkhan.modmanager.gui.widgets.base.BaseLabel();
        profilesComboBox = new com.shoaibkhan.modmanager.gui.widgets.profile.ProfilesComboBox();
        addProfileButton = new com.shoaibkhan.modmanager.gui.widgets.profile.AddProfileButton();
        removeProfileButton = new com.shoaibkhan.modmanager.gui.widgets.profile.RemoveProfileButton();

        setNextFocusableComponent(hLabel);

        hLabel.setText("Select Profile:-   ");
        hLabel.setNextFocusableComponent(profilesComboBox);
        add(hLabel);

        profilesComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        profilesComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        profilesComboBox.setNextFocusableComponent(addProfileButton);
        add(profilesComboBox);

        addProfileButton.setText("Add Profile");
        addProfileButton.setToolTipText("");
        addProfileButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addProfileButton.setNextFocusableComponent(removeProfileButton);
        addProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfileButtonActionPerformed(evt);
            }
        });
        add(addProfileButton);

        removeProfileButton.setText("Remove Profile");
        removeProfileButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(removeProfileButton);
    }// </editor-fold>//GEN-END:initComponents

    private void addProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProfileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shoaibkhan.modmanager.gui.widgets.profile.AddProfileButton addProfileButton;
    private com.shoaibkhan.modmanager.gui.widgets.base.BaseLabel hLabel;
    public static com.shoaibkhan.modmanager.gui.widgets.profile.ProfilesComboBox profilesComboBox;
    private com.shoaibkhan.modmanager.gui.widgets.profile.RemoveProfileButton removeProfileButton;
    // End of variables declaration//GEN-END:variables
}
