#!/bin/sh

# Download the latest release file
curl -L https://github.com/accessible-minecraft/mod-manager/releases/latest/download/Mod.Manager.zip --output Temp.Mod.Manager.zip

# Extract it
unzip -d ./temp/ ./Temp.Mod.Manager

# Move the new files
rsync -a ./temp/Mod\ Manager/* ../
rm -rf ./temp/Mod\ Manager/*

# Give executable permission to files
chmod 777 ./update-on-unix
sed -i -e 's/\r$//' ./update-on-unix
chmod 777 ../run-on-unix
sed -i -e 's/\r$//' ../run-on-unix

# Delete temperory files
rm -rf Temp.Mod.Manager.zip temp