#!/bin/sh

# Download the latest release file
curl -L https://github.com/accessible-minecraft/mod-manager/releases/latest/download/Mod.Manager.zip --output Temp.Mod.Manager.zip

# Extract it
unzip -d ./temp/ ./Temp.Mod.Manager

# Move the new files
mv -f ./temp/Mod\ Manager/* ../

# Delete temperory files
rm -rf Temp.Mod.Manager.zip temp